
prompt_keff = """
Q:Please select the relationship between the two entities in the question from the relation list : question:As of 21 April 2015 12:00 am, the airport of Örnsköldsvik/Gideå (OER/ESNO) is run using remote ATC services from Sundsvall/Midlanda (SDL/ESNN).\n
entity1:OER, eneity2:Örnsköldsvik.\n
relation_list:1.place served by transport hub 2.mountain range 3.religion 4.participating team 5.contains administrative territorial entity 6.head of government 7.country of citizenship 8.original network 9.heritage designation 10.performer 11.participant of 12.position held 13.has part 14.location of formation 15.located on terrain feature 16.architect 17.country of origin 18.publisher 19.director 20.father 21.developer 22.military branch 23.mouth of the watercourse 24.nominated for 25.movement 26.successful candidate 27.followed by 28.manufacturer 29.instance of 30.after a work by 31.member of political party 32.licensed to broadcast to 33.headquarters location 34.sibling 35.instrument 36.country 37.occupation 38.residence 39.work location 40.subsidiary 41.participant 42.operator 43.characters 44.occupant 45.genre 46.operating system 47.owned by 48.platform 49.tributary 50.winner 51.said to be the same as 52.composer 53.league 54.record label 55.distributor 56.screenwriter 57.sports season of league or competition 58.taxon rank 59.location 60.field of work 61.language of work or name 62.applies to jurisdiction 63.notable work 64.located in the administrative territorial entity 65.crosses 66.original language of film or TV show 67.competition class 68.part of 69.sport 70.constellation 71.position played on team / speciality 72.located in or next to body of water 73.voice type 74.follows 75.spouse 76.military rank 77.mother 78.member of 79.child 80.main subject.\n
A:the relation is {place served by transport hub}

Q:Please select the relationship between the two entities in the question from the relation list : question:The Pârâul Sterp is a tributary of the Pârâul Alb in Romania.\n
entity1:Pârâul Sterp, eneity2:Pârâul Alb.\n
relation_list:1.place served by transport hub 2.mountain range 3.religion 4.participating team 5.contains administrative territorial entity 6.head of government 7.country of citizenship 8.original network 9.heritage designation 10.performer 11.participant of 12.position held 13.has part 14.location of formation 15.located on terrain feature 16.architect 17.country of origin 18.publisher 19.director 20.father 21.developer 22.military branch 23.mouth of the watercourse 24.nominated for 25.movement 26.successful candidate 27.followed by 28.manufacturer 29.instance of 30.after a work by 31.member of political party 32.licensed to broadcast to 33.headquarters location 34.sibling 35.instrument 36.country 37.occupation 38.residence 39.work location 40.subsidiary 41.participant 42.operator 43.characters 44.occupant 45.genre 46.operating system 47.owned by 48.platform 49.tributary 50.winner 51.said to be the same as 52.composer 53.league 54.record label 55.distributor 56.screenwriter 57.sports season of league or competition 58.taxon rank 59.location 60.field of work 61.language of work or name 62.applies to jurisdiction 63.notable work 64.located in the administrative territorial entity 65.crosses 66.original language of film or TV show 67.competition class 68.part of 69.sport 70.constellation 71.position played on team / speciality 72.located in or next to body of water 73.voice type 74.follows 75.spouse 76.military rank 77.mother 78.member of 79.child 80.main subject.\n
A:the relation is {mouth of the watercourse}

Q:Please select the relationship between the two entities in the question from the relation list : question:Under the Justinian Dynasty, particularly the reign of Justinian I, the Empire reached its largest territorial point, reincorporating North Africa, southern Illyria, southern Spain, and Italy into the Empire.\n
entity1:Italy, eneity2:Justinian I.\n
relation_list:1.place served by transport hub 2.mountain range 3.religion 4.participating team 5.contains administrative territorial entity 6.head of government 7.country of citizenship 8.original network 9.heritage designation 10.performer 11.participant of 12.position held 13.has part 14.location of formation 15.located on terrain feature 16.architect 17.country of origin 18.publisher 19.director 20.father 21.developer 22.military branch 23.mouth of the watercourse 24.nominated for 25.movement 26.successful candidate 27.followed by 28.manufacturer 29.instance of 30.after a work by 31.member of political party 32.licensed to broadcast to 33.headquarters location 34.sibling 35.instrument 36.country 37.occupation 38.residence 39.work location 40.subsidiary 41.participant 42.operator 43.characters 44.occupant 45.genre 46.operating system 47.owned by 48.platform 49.tributary 50.winner 51.said to be the same as 52.composer 53.league 54.record label 55.distributor 56.screenwriter 57.sports season of league or competition 58.taxon rank 59.location 60.field of work 61.language of work or name 62.applies to jurisdiction 63.notable work 64.located in the administrative territorial entity 65.crosses 66.original language of film or TV show 67.competition class 68.part of 69.sport 70.constellation 71.position played on team / speciality 72.located in or next to body of water 73.voice type 74.follows 75.spouse 76.military rank 77.mother 78.member of 79.child 80.main subject.\n
A:the relation is {part of}

Q:Please select the relationship between the two entities in the question from the relation list : question:$question\n
entity1:$entity1, eneity2:$entity2\n
relation_list:1.place served by transport hub 2.mountain range 3.religion 4.participating team 5.contains administrative territorial entity 6.head of government 7.country of citizenship 8.original network 9.heritage designation 10.performer 11.participant of 12.position held 13.has part 14.location of formation 15.located on terrain feature 16.architect 17.country of origin 18.publisher 19.director 20.father 21.developer 22.military branch 23.mouth of the watercourse 24.nominated for 25.movement 26.successful candidate 27.followed by 28.manufacturer 29.instance of 30.after a work by 31.member of political party 32.licensed to broadcast to 33.headquarters location 34.sibling 35.instrument 36.country 37.occupation 38.residence 39.work location 40.subsidiary 41.participant 42.operator 43.characters 44.occupant 45.genre 46.operating system 47.owned by 48.platform 49.tributary 50.winner 51.said to be the same as 52.composer 53.league 54.record label 55.distributor 56.screenwriter 57.sports season of league or competition 58.taxon rank 59.location 60.field of work 61.language of work or name 62.applies to jurisdiction 63.notable work 64.located in the administrative territorial entity 65.crosses 66.original language of film or TV show 67.competition class 68.part of 69.sport 70.constellation 71.position played on team / speciality 72.located in or next to body of water 73.voice type 74.follows 75.spouse 76.military rank 77.mother 78.member of 79.child 80.main subject.\n
A:
"""